// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-courses.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient } from "npm:@supabase/supabase-js@^2.108.2";
import { z } from "npm:zod@^3.25.76";
function anonSupabase() {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
var list_courses_default = defineTool({
  name: "list_courses",
  title: "List courses",
  description: "List published, approved courses on AI Coach Portal. Optional search by keyword and filter by category or level.",
  inputSchema: {
    search: z.string().trim().optional().describe("Keyword to search title/subtitle/description."),
    category: z.string().trim().optional().describe("Category slug or name to filter by."),
    level: z.string().trim().optional().describe("Course level (e.g. Beginner, Intermediate, Advanced)."),
    limit: z.number().int().min(1).max(50).optional().describe("Max results (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, category, level, limit }) => {
    const sb = anonSupabase();
    let q = sb.from("courses").select("id, slug, title, subtitle, category, level, language, duration_hours, price_usd, price_inr, thumbnail_url").eq("is_published", true).eq("approval_status", "approved").limit(limit ?? 20);
    if (search) q = q.or(`title.ilike.%${search}%,subtitle.ilike.%${search}%,description.ilike.%${search}%`);
    if (category) q = q.ilike("category", `%${category}%`);
    if (level) q = q.ilike("level", `%${level}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { courses: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/search-coaches.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.108.2";
import { z as z2 } from "npm:zod@^3.25.76";
function anonSupabase2() {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
var search_coaches_default = defineTool2({
  name: "search_coaches",
  title: "Search coaches",
  description: "Search public coach profiles on AI Coach Portal by keyword, category, city, or country.",
  inputSchema: {
    search: z2.string().trim().optional().describe("Keyword matched against name, bio, job title."),
    category: z2.string().trim().optional(),
    city: z2.string().trim().optional(),
    country: z2.string().trim().optional(),
    limit: z2.number().int().min(1).max(50).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, category, city, country, limit }) => {
    const sb = anonSupabase2();
    let q = sb.from("coach_public_profiles").select("id, user_id, full_name, slug, avatar_url, bio, category, job_title, company_name, industry, country, city, tags").limit(limit ?? 20);
    if (search) q = q.or(`full_name.ilike.%${search}%,bio.ilike.%${search}%,job_title.ilike.%${search}%`);
    if (category) q = q.ilike("category", `%${category}%`);
    if (city) q = q.ilike("city", `%${city}%`);
    if (country) q = q.ilike("country", `%${country}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { coaches: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/my-enrollments.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.108.2";
function userSupabase(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var my_enrollments_default = defineTool3({
  name: "my_enrollments",
  title: "My enrollments",
  description: "List courses the signed-in learner is enrolled in, with progress and payment status.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = userSupabase(ctx);
    const { data, error } = await sb.from("enrollments").select("id, course_id, progress_percent, payment_status, amount_paid, currency, enrolled_at, completed_at, courses(title, slug, thumbnail_url)").eq("learner_id", ctx.getUserId()).order("enrolled_at", { ascending: false }).limit(100);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { enrollments: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/my-profile.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.108.2";
function userSupabase2(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var my_profile_default = defineTool4({
  name: "my_profile",
  title: "My profile",
  description: "Return the signed-in user's profile record from AI Coach Portal.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = userSupabase2(ctx);
    const [{ data: profile, error: pErr }, { data: roles }] = await Promise.all([
      sb.from("profiles").select("*").eq("id", ctx.getUserId()).maybeSingle(),
      sb.from("user_roles").select("role").eq("user_id", ctx.getUserId())
    ]);
    if (pErr) return { content: [{ type: "text", text: pErr.message }], isError: true };
    const result = { profile, roles: (roles ?? []).map((r) => r.role), email: ctx.getUserEmail() };
    return {
      content: [{ type: "text", text: JSON.stringify(result) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "iipxwwrzkdkestikxcpg";
var mcp_default = defineMcp({
  name: "ai-coach-portal-mcp",
  title: "AI Coach Portal",
  version: "0.1.0",
  instructions: "Tools for AI Coach Portal \u2014 the AI coaching marketplace. Use `list_courses` and `search_coaches` to explore the public catalog. Authenticated learners can use `my_enrollments` and `my_profile` to access their own data.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_courses_default, search_coaches_default, my_enrollments_default, my_profile_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
